# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20190521_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-bio']},
        ),
    ]
