# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 02:02
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20190523_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
